### ISSUE TITLE
remove tests which can't be run directly

### ISSUE THREAD

**Issue by MarcoGorelli** [raisadz/pandas-coverage#6]
all the tests in pandas/tests/extension/base can't be run directly and are meant to be subclassed. perhaps we can just exclude them from the app then?

maybe we can just exclude test classes that don't start with `Test` and test functions that don't start with `test`

**Comment by MarcoGorelli** [comment]
can also remove hypothesis tests, such as `hypothesis.internal.conjecture.engine.ConjectureRunner.test_function`

**Comment by MarcoGorelli** [comment]
and also: pandas/tests/arrays/test_datetimelike.py::SharedTests::test_median

**Comment by MarcoGorelli** [comment]
finally, the numbers aren't that useful on the side, so maybe they can be removed as well? perhaps `st.table` isn't the best container for the list of tests

**Comment by MarcoGorelli** [comment]
I think what could be done is that in 

https://github.com/raisadz/pandas-coverage/blob/b2bf36acabe48b47d12e4e0dfc03375b2d615e63/main.py#L54-L70

in the 

```
*pieces[n_range:]
```

part, we check that each element starts with `Test` or `test`. If it doesn't, we exclude it

**Comment by raisadz** [comment]
Closed by #7
